"""Typer CLI for auto-gen-py-project.

Commands mirror the public UX described in the README:
``init``, ``create``, ``new``, template/plugin helpers, ``doctor``, etc.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Optional

import typer
from rich.panel import Panel
from rich.prompt import Confirm, Prompt
from rich.table import Table

from auto_gen_py_project import __version__
from auto_gen_py_project.ai import AIService
from auto_gen_py_project.config import load_preferences, save_preferences
from auto_gen_py_project.core.exceptions import AutoGenError
from auto_gen_py_project.core.generator import ProjectGenerator
from auto_gen_py_project.core.models import (
    LicenseType,
    PackageManager,
    ProjectSpec,
    ProjectType,
    UserPreferences,
)
from auto_gen_py_project.logging import get_console, get_logger, setup_logging
from auto_gen_py_project.plugins import PluginManager
from auto_gen_py_project.templates import TemplateRegistry
from auto_gen_py_project.utilities import ensure_dir

app = typer.Typer(
    name="auto-gen-py-project",
    help="Generate production-ready Python projects from templates.",
    no_args_is_help=True,
    add_completion=False,
    rich_markup_mode="rich",
)
plugin_app = typer.Typer(help="Manage plugins.")
app.add_typer(plugin_app, name="plugin")

console = get_console()


# Display name shown in version / UI (CLI entry point remains auto-gen-py-project)
DISPLAY_NAME = "Auto-Gen-Py-Project"


def _print_version() -> None:
    """Print the installed package version (plain + panel)."""
    # Plain line first so shells / scripts can parse easily
    console.print(f"{DISPLAY_NAME} {__version__}")
    console.print(Panel(f"[bold cyan]{__version__}[/]", title=DISPLAY_NAME))


def _version_option(value: bool) -> None:
    """Eager ``--version`` / ``-V`` handler."""
    if value:
        _print_version()
        raise typer.Exit()


@app.callback()
def _root(
    version: bool = typer.Option(
        False,
        "--version",
        "-V",
        help="Show version and exit.",
        callback=_version_option,
        is_eager=True,
    ),
) -> None:
    """Generate production-ready Python projects from templates."""
    # Callback exists so --version works on the root command.
    _ = version


def _prefs() -> UserPreferences:
    prefs, _ = load_preferences()
    return prefs


def _spec_from_prefs(
    name: str,
    *,
    project_type: ProjectType,
    prefs: UserPreferences,
    package_name: Optional[str] = None,
    description: Optional[str] = None,
) -> ProjectSpec:
    pkg = package_name or ProjectSpec.normalize_package_name(name)
    return ProjectSpec(
        name=name,
        package_name=pkg,
        project_type=project_type,
        description=description or f"{name} — generated by auto-gen-py-project",
        author=prefs.author,
        email=prefs.email,
        license=prefs.license,
        python_version=prefs.python_version,
        package_manager=prefs.package_manager,
        testing_framework=prefs.testing_framework,
        formatter=prefs.formatter,
        linter=prefs.linter,
        type_checker=prefs.type_checker,
        ci_provider=prefs.ci_provider,
        use_docker=prefs.use_docker,
        use_precommit=prefs.use_precommit,
        use_git=prefs.use_git,
        create_venv=prefs.create_venv,
        install_deps=prefs.install_deps,
        generate_lock=prefs.generate_lock,
    )


def _interactive_spec(prefs: UserPreferences, default_name: str = "MyProject") -> tuple[ProjectSpec, Path]:
    console.print(Panel(f"[bold cyan]{DISPLAY_NAME}[/] interactive wizard", subtitle="create"))
    name = Prompt.ask("Project name", default=default_name)
    package_name = Prompt.ask("Package name", default=ProjectSpec.normalize_package_name(name))
    description = Prompt.ask("Description", default=f"{name} Python project")

    table = Table(title="Project types")
    table.add_column("#", style="cyan")
    table.add_column("Type")
    types = list(ProjectType)
    for i, t in enumerate(types, 1):
        table.add_row(str(i), t.value)
    console.print(table)
    idx = Prompt.ask("Select type number", default="1")
    try:
        project_type = types[int(idx) - 1]
    except (ValueError, IndexError):
        project_type = ProjectType.LIBRARY

    author = Prompt.ask("Author", default=prefs.author)
    email = Prompt.ask("Email", default=prefs.email)
    license_name = Prompt.ask("License", default=prefs.license.value)
    try:
        license_type = LicenseType(license_name)
    except ValueError:
        license_type = prefs.license

    python_version = Prompt.ask("Python version", default=prefs.python_version)
    pm = Prompt.ask(
        "Package manager (pip/uv/poetry/hatch/pdm)",
        default=prefs.package_manager.value,
    )
    try:
        package_manager = PackageManager(pm)
    except ValueError:
        package_manager = PackageManager.PIP

    generate_lock = False
    if package_manager in (PackageManager.UV, PackageManager.POETRY):
        generate_lock = Confirm.ask(
            f"Generate {package_manager.value} lockfile?",
            default=prefs.generate_lock,
        )

    use_docker = Confirm.ask("Include Docker?", default=prefs.use_docker)
    use_git = Confirm.ask("Initialize git?", default=prefs.use_git)
    create_venv = Confirm.ask("Create virtualenv?", default=prefs.create_venv)
    install_deps = Confirm.ask("Install dependencies now?", default=prefs.install_deps)
    dest_default = str(Path.cwd() / ProjectSpec.normalize_package_name(name).replace("_", "-"))
    dest = Path(Prompt.ask("Output directory", default=dest_default))

    spec = ProjectSpec(
        name=name,
        package_name=package_name,
        project_type=project_type,
        description=description,
        author=author,
        email=email,
        license=license_type,
        python_version=python_version,
        package_manager=package_manager,
        generate_lock=generate_lock,
        use_docker=use_docker,
        use_compose=use_docker and Confirm.ask("Include docker-compose?", default=False),
        use_git=use_git,
        create_venv=create_venv,
        install_deps=install_deps,
        use_precommit=prefs.use_precommit,
        ci_provider=prefs.ci_provider,
        testing_framework=prefs.testing_framework,
        formatter=prefs.formatter,
        linter=prefs.linter,
        type_checker=prefs.type_checker,
    )
    return spec, dest


def _resolve_template(template: str) -> tuple[ProjectType, str]:
    """Return (project_type, template_id) for built-in or plugin templates."""
    try:
        return ProjectType(template), template
    except ValueError:
        pass
    mgr = PluginManager()
    mgr.load_entry_points()
    registry = TemplateRegistry(mgr.extra_template_roots)
    try:
        found = registry.get(template)
        if found.project_types:
            try:
                ptype = ProjectType(found.project_types[0])
            except ValueError:
                ptype = ProjectType.LIBRARY
        else:
            ptype = ProjectType.LIBRARY
        return ptype, found.id
    except Exception:  # noqa: BLE001
        console.print(f"[yellow]Unknown template '{template}', using library[/]")
        return ProjectType.LIBRARY, "library"


def _run_generate(
    spec: ProjectSpec,
    dest: Path,
    *,
    force: bool = False,
    prompt: str = "",
    template_id: Optional[str] = None,
) -> None:
    setup_logging()
    gen = ProjectGenerator()
    path = gen.generate(
        spec,
        dest,
        force=force,
        apply_ai=bool(prompt),
        prompt=prompt,
        template_id=template_id,
    )
    console.print(Panel(f"[green]Created[/] {path}", title=DISPLAY_NAME))


@app.command("init")
def init_cmd(
    path: Optional[Path] = typer.Argument(
        None,
        help="Project root directory. Omit to create a new folder for a simple Python project.",
    ),
    name: Optional[str] = typer.Option(None, "--name", "-n", help="Project name (also used for folder name when PATH is omitted)"),
    template: str = typer.Option(
        "library",
        "--template",
        "-t",
        help="Template / project type (default: simple library)",
    ),
    package_manager: Optional[str] = typer.Option(
        None, "--package-manager", "-m", help="pip|uv|poetry|hatch|pdm"
    ),
    lock: bool = typer.Option(False, "--lock", help="Generate uv.lock or poetry.lock"),
    force: bool = typer.Option(False, "--force"),
    debug: bool = typer.Option(False, "--debug"),
) -> None:
    """Create a simple Python project, including the root folder when needed.

    Plain ``init`` (no PATH) creates ``./<name>/`` with a library scaffold inside.
    With a PATH, that directory is created if missing and filled with the project.
    """
    setup_logging(debug=debug)
    prefs = _prefs()

    # Plain `init`: create a new root folder under cwd, then scaffold inside it.
    if path is None:
        project_name = name or "my-project"
        folder = ProjectSpec.normalize_package_name(project_name).replace("_", "-")
        dest = Path.cwd() / folder
    else:
        dest = path
        if name:
            project_name = name
        elif str(path) in (".", ""):
            project_name = Path.cwd().resolve().name
        else:
            project_name = path.name or "my-project"

    # Ensure the project root folder exists before generation.
    dest = dest.resolve()
    dest.mkdir(parents=True, exist_ok=True)

    ptype, template_id = _resolve_template(template)
    spec = _spec_from_prefs(project_name, project_type=ptype, prefs=prefs)
    # Keep plain init simple: no auto-install / venv unless prefs already ask for them
    if package_manager:
        try:
            spec.package_manager = PackageManager(package_manager)
        except ValueError:
            console.print(
                f"[yellow]Unknown package manager '{package_manager}', "
                f"using {spec.package_manager.value}[/]"
            )
    if lock:
        spec.generate_lock = True
    try:
        _run_generate(spec, dest, force=force, template_id=template_id)
    except AutoGenError as exc:
        console.print(f"[red]{exc.message}[/]")
        raise typer.Exit(1) from exc


@app.command("create")
def create_cmd(
    debug: bool = typer.Option(False, "--debug"),
) -> None:
    """Interactive project creation wizard."""
    setup_logging(debug=debug)
    prefs = _prefs()
    try:
        spec, dest = _interactive_spec(prefs)
        if dest.exists() and any(dest.iterdir()):
            if not Confirm.ask(f"{dest} is not empty. Continue / overwrite?", default=False):
                raise typer.Exit(0)
            force = True
        else:
            force = False
        _run_generate(spec, dest, force=force)
    except AutoGenError as exc:
        console.print(f"[red]{exc.message}[/]")
        raise typer.Exit(1) from exc


@app.command("new")
def new_cmd(
    name: str = typer.Argument(..., help="Project name"),
    template: str = typer.Option("library", "--template", "-t"),
    path: Optional[Path] = typer.Option(None, "--path", "-p"),
    description: Optional[str] = typer.Option(None, "--description", "-d"),
    package_manager: Optional[str] = typer.Option(
        None, "--package-manager", "-m", help="pip|uv|poetry|hatch|pdm"
    ),
    lock: bool = typer.Option(False, "--lock", help="Generate uv.lock or poetry.lock"),
    docker: bool = typer.Option(False, "--docker"),
    no_git: bool = typer.Option(False, "--no-git"),
    venv: bool = typer.Option(False, "--venv"),
    install: bool = typer.Option(False, "--install"),
    ai_prompt: Optional[str] = typer.Option(
        None,
        "--describe",
        help="Optional free-text description used to pick a template by keywords",
    ),
    force: bool = typer.Option(False, "--force"),
    debug: bool = typer.Option(False, "--debug"),
) -> None:
    """Create a new project non-interactively."""
    setup_logging(debug=debug)
    prefs = _prefs()
    try:
        ptype = ProjectType(template)
        template_id = template
    except ValueError:
        if ai_prompt:
            ptype = AIService().recommend_template(ai_prompt)
            template_id = ptype.value
        else:
            ptype, template_id = _resolve_template(template)
    spec = _spec_from_prefs(name, project_type=ptype, prefs=prefs, description=description)
    if package_manager:
        try:
            spec.package_manager = PackageManager(package_manager)
        except ValueError:
            console.print(
                f"[yellow]Unknown package manager '{package_manager}', "
                f"using {spec.package_manager.value}[/]"
            )
    if lock:
        spec.generate_lock = True
    spec.use_docker = docker or prefs.use_docker
    spec.use_git = (not no_git) and prefs.use_git
    spec.create_venv = venv or prefs.create_venv
    spec.install_deps = install or prefs.install_deps
    dest = path or (Path.cwd() / ProjectSpec.normalize_package_name(name).replace("_", "-"))
    try:
        _run_generate(spec, dest, force=force, prompt=ai_prompt or "", template_id=template_id)
    except AutoGenError as exc:
        console.print(f"[red]{exc.message}[/]")
        raise typer.Exit(1) from exc


@app.command("list-templates")
def list_templates_cmd() -> None:
    """List available project templates."""
    setup_logging()
    plugins = PluginManager()
    plugins.load_entry_points()
    registry = TemplateRegistry(plugins.extra_template_roots)
    table = Table(title="Templates")
    table.add_column("ID")
    table.add_column("Name")
    table.add_column("Description")
    table.add_column("Types")
    for meta in registry.list():
        table.add_row(meta.id, meta.name, meta.description, ", ".join(meta.project_types))
    # Also show all project types as logical templates
    console.print(table)
    console.print("\n[dim]All ProjectType values are available via --template[/]")
    for t in ProjectType:
        console.print(f"  • {t.value}")


@app.command("install-template")
def install_template_cmd(
    name: str = typer.Argument(..., help="Template id or plugin package hint"),
) -> None:
    """Install a template plugin package (pip) or copy a named starter."""
    setup_logging()
    pkg = name if name.startswith("auto-gen-py-project-") else f"auto-gen-py-project-{name}"
    console.print(f"Attempting to install [cyan]{pkg}[/] …")
    code = subprocess.call([sys.executable, "-m", "pip", "install", pkg])
    if code != 0:
        # Fallback: install a local sample custom template into user dir
        user_dir = Path.home() / ".config" / "auto-gen-py-project" / "templates" / name
        ensure_dir(user_dir)
        sample = Path(__file__).resolve().parents[1] / "templates" / "_sample_custom"
        if sample.is_dir():
            if user_dir.exists():
                shutil.rmtree(user_dir)
            shutil.copytree(sample, user_dir)
            # rewrite id
            meta = user_dir / "template.json"
            if meta.exists():
                data = json.loads(meta.read_text(encoding="utf-8"))
                data["id"] = name
                data["name"] = name
                meta.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
            console.print(f"[yellow]PyPI package not found.[/] Installed local sample template at {user_dir}")
        else:
            console.print(f"[red]Could not install template '{name}'[/]")
            raise typer.Exit(1)
    else:
        console.print(f"[green]Installed[/] {pkg}")


@app.command("doctor")
def doctor_cmd() -> None:
    """Diagnose environment health."""
    import platform
    import sysconfig

    setup_logging()
    table = Table(title="Doctor")
    table.add_column("Check")
    table.add_column("Result")
    table.add_row(DISPLAY_NAME, __version__)
    table.add_row("python", sys.version.split()[0])
    table.add_row(
        "os",
        f"{platform.system()} {platform.release()} ({sys.platform})",
    )
    table.add_row("supported platforms", "Windows, macOS, Linux")
    cli_path = shutil.which("auto-gen-py-project")
    table.add_row("cli on PATH", cli_path or "[red]not found[/]")
    for tool in ("git", "docker", "uv", "poetry", "pdm", "hatch"):
        table.add_row(tool, shutil.which(tool) or "[dim]not found[/]")
    prefs, path = load_preferences()
    table.add_row("config", str(path) if path else "[dim]defaults[/]")
    table.add_row("author", prefs.author)
    plugins = PluginManager()
    plugins.load_entry_points()
    table.add_row("plugins", str(len(plugins.plugins)))
    table.add_row("templates", str(len(TemplateRegistry(plugins.extra_template_roots).list())))
    console.print(table)
    # User installs may put the console script outside PATH on any OS
    if not cli_path:
        candidates: list[Path] = []
        for scheme in (None, "nt_user", "posix_user", "osx_framework_user"):
            try:
                raw = (
                    sysconfig.get_path("scripts")
                    if scheme is None
                    else sysconfig.get_path("scripts", scheme=scheme)
                )
            except Exception:  # noqa: BLE001
                continue
            if raw:
                p = Path(raw)
                if p not in candidates:
                    candidates.append(p)
        lines = "\n".join(f"  {p}" for p in candidates) or "  (see python -m site)"
        tip = candidates[-1] if candidates else Path("Scripts")
        if sys.platform == "win32":
            path_help = (
                "PowerShell (user PATH), then open a new terminal:\n"
                f"  [Environment]::SetEnvironmentVariable(\n"
                f"    'Path', $env:Path + ';{tip}', 'User')"
            )
        else:
            path_help = (
                "bash/zsh (add to ~/.bashrc or ~/.zshrc), then reload the shell:\n"
                f'  export PATH="{tip}:$PATH"'
            )
        console.print(
            Panel(
                f"[yellow]Command `auto-gen-py-project` is not on PATH.[/]\n\n"
                f"Works on Windows, macOS, and Linux.\n"
                f"Use: [bold]python -m auto_gen_py_project version[/]\n\n"
                f"Or add a scripts folder to PATH:\n"
                f"{lines}\n\n"
                f"{path_help}",
                title="PATH fix",
            )
        )


@app.command("update")
def update_cmd() -> None:
    """Update auto-gen-py-project from PyPI."""
    setup_logging()
    code = subprocess.call(
        [sys.executable, "-m", "pip", "install", "--upgrade", "auto-gen-py-project"]
    )
    if code == 0:
        console.print(f"[green]Updated.[/] Check with: python -m auto_gen_py_project version")
        if not shutil.which("auto-gen-py-project"):
            console.print(
                "[dim]Tip: if `auto-gen-py-project` is not found, use "
                "`python -m auto_gen_py_project …` or run `doctor` for PATH help.[/]"
            )
    raise typer.Exit(code)


@app.command("version")
def version_cmd() -> None:
    """Show installed package version (`auto-gen-py-project version`)."""
    _print_version()


@app.command("config")
def config_cmd(
    show: bool = typer.Option(True, "--show/--edit", help="Show or write defaults"),
    path: Optional[Path] = typer.Option(None, "--path"),
) -> None:
    """Show or initialize user configuration."""
    setup_logging()
    prefs, existing = load_preferences(path)
    if show and not path:
        console.print_json(data=prefs.model_dump(mode="json"))
        if existing:
            console.print(f"[dim]Loaded from {existing}[/]")
        return
    target = path or (Path.home() / ".config" / "auto-gen-py-project" / "auto-gen-py-project.toml")
    save_preferences(prefs, target)
    console.print(f"[green]Wrote[/] {target}")


@plugin_app.command("list")
def plugin_list_cmd() -> None:
    """List discovered plugins."""
    setup_logging()
    mgr = PluginManager()
    mgr.load_entry_points()
    items = mgr.list_installed()
    if not items:
        console.print("[dim]No plugins installed.[/]")
        console.print("Install with: pip install auto-gen-py-project-<name>")
        return
    table = Table(title="Plugins")
    table.add_column("Name")
    table.add_column("Version")
    table.add_column("Description")
    for item in items:
        table.add_row(item["name"], item["version"], item["description"])
    console.print(table)


@plugin_app.command("install")
def plugin_install_cmd(name: str = typer.Argument(...)) -> None:
    """Install a plugin package from PyPI."""
    pkg = name if name.startswith("auto-gen-py-project-") else f"auto-gen-py-project-{name}"
    raise typer.Exit(subprocess.call([sys.executable, "-m", "pip", "install", pkg]))


@plugin_app.command("remove")
def plugin_remove_cmd(name: str = typer.Argument(...)) -> None:
    """Uninstall a plugin package."""
    pkg = name if name.startswith("auto-gen-py-project-") else f"auto-gen-py-project-{name}"
    raise typer.Exit(subprocess.call([sys.executable, "-m", "pip", "uninstall", "-y", pkg]))


def main() -> None:
    # Attach plugin CLI contributions
    mgr = PluginManager()
    try:
        mgr.load_entry_points()
        mgr.attach_cli(app)
    except Exception:  # noqa: BLE001
        pass
    app()


if __name__ == "__main__":
    main()
