"""Domain models for project generation.

``LicenseType`` values are options offered to *generated* projects; the
generator package itself is MIT-licensed (see ``LICENSE``).
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field


class ProjectType(str, Enum):
    LIBRARY = "library"
    CLI = "cli"
    FASTAPI = "fastapi"
    FLASK = "flask"
    DJANGO = "django"
    DATA_SCIENCE = "data-science"
    MACHINE_LEARNING = "machine-learning"
    AI = "ai"
    COMPUTER_VISION = "computer-vision"
    REST_API = "rest-api"
    MICROSERVICE = "microservice"
    DESKTOP = "desktop"
    AUTOMATION = "automation"
    ASYNC = "async"
    PYPI_PACKAGE = "pypi-package"
    JUPYTER = "jupyter"


class PackageManager(str, Enum):
    PIP = "pip"
    UV = "uv"
    POETRY = "poetry"
    HATCH = "hatch"
    PDM = "pdm"


class LicenseType(str, Enum):
    MIT = "MIT"
    APACHE2 = "Apache-2.0"
    GPL3 = "GPL-3.0"
    AGPL3 = "AGPL-3.0"
    BSD3 = "BSD-3-Clause"
    UNLICENSE = "Unlicense"
    PROPRIETARY = "Proprietary"


class ProjectSpec(BaseModel):
    """Fully resolved specification used to render a project."""

    name: str = Field(..., description="Human-readable project name")
    package_name: str = Field(..., description="Importable Python package name")
    project_type: ProjectType = ProjectType.LIBRARY
    description: str = "A Python project generated by auto-gen-py-project"
    version: str = "0.1.0"
    author: str = "Author"
    email: str = "author@example.com"
    license: LicenseType = LicenseType.MIT
    python_version: str = "3.12"
    package_manager: PackageManager = PackageManager.PIP
    testing_framework: str = "pytest"
    formatter: str = "ruff"
    linter: str = "ruff"
    type_checker: str = "mypy"
    ci_provider: str = "github-actions"
    use_docker: bool = False
    use_compose: bool = False
    use_precommit: bool = True
    use_git: bool = True
    create_venv: bool = False
    install_deps: bool = False
    vscode: bool = True
    pycharm: bool = False
    extras: dict[str, Any] = Field(default_factory=dict)

    @staticmethod
    def normalize_package_name(name: str) -> str:
        cleaned = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in name.strip())
        cleaned = cleaned.lower().strip("_")
        if cleaned and cleaned[0].isdigit():
            cleaned = f"pkg_{cleaned}"
        return cleaned or "my_project"

    def template_context(self) -> dict[str, Any]:
        """Context dict passed to Jinja2 templates."""
        return {
            "name": self.name,
            "package_name": self.package_name,
            "project_slug": self.package_name.replace("_", "-"),
            "project_type": self.project_type.value,
            "description": self.description,
            "version": self.version,
            "author": self.author,
            "email": self.email,
            "license": self.license.value,
            "python_version": self.python_version,
            "package_manager": self.package_manager.value,
            "testing_framework": self.testing_framework,
            "formatter": self.formatter,
            "linter": self.linter,
            "type_checker": self.type_checker,
            "ci_provider": self.ci_provider,
            "use_docker": self.use_docker,
            "use_compose": self.use_compose,
            "use_precommit": self.use_precommit,
            "use_git": self.use_git,
            "vscode": self.vscode,
            "pycharm": self.pycharm,
            **self.extras,
        }


class UserPreferences(BaseModel):
    """Persisted user defaults from config files."""

    author: str = "Author"
    email: str = "author@example.com"
    license: LicenseType = LicenseType.MIT
    python_version: str = "3.12"
    package_manager: PackageManager = PackageManager.PIP
    testing_framework: str = "pytest"
    formatter: str = "ruff"
    linter: str = "ruff"
    type_checker: str = "mypy"
    ci_provider: str = "github-actions"
    use_docker: bool = False
    use_precommit: bool = True
    use_git: bool = True
    create_venv: bool = False
    install_deps: bool = False
    default_template: Optional[str] = "library"
    template_dirs: list[str] = Field(default_factory=list)
